Revert changes to omap_stop_dma
They were causing the following errors:
arch/arm/plat-omap/dma.c: In function 'omap_stop_dma':
arch/arm/plat-omap/dma.c:712: error: 'DMA_SYSCONFIG_MIDLEMODE_MASK' undeclared (first use in this function)
arch/arm/plat-omap/dma.c:712: error: (Each undeclared identifier is reported only once
arch/arm/plat-omap/dma.c:712: error: for each function it appears in.)
arch/arm/plat-omap/dma.c:713: error: implicit declaration of function 'DMA_SYSCONFIG_MIDLEMODE'
arch/arm/plat-omap/dma.c:713: error: 'DMA_IDLEMODE_NO_IDLE' undeclared (first use in this function)