Revert changes to musb_dma_completion
They were causing the following errors:
drivers/usb/musb/musb_core.c: In function 'musb_dma_completion':
drivers/usb/musb/musb_core.c:1804: error: 'musb_base' undeclared (first use in this function)
drivers/usb/musb/musb_core.c:1804: error: (Each undeclared identifier is reported only once
drivers/usb/musb/musb_core.c:1804: error: for each function it appears in.)
drivers/usb/musb/musb_core.c:1804: error: 'struct musb' has no member named 'context'